Repository paritytech/parity-bitcoin, pull requests merged in 2018-04, with the labels that each got.

#496 Bitcoin Cash: OP_BIN2NUM implementation
  script/src/flags.rs
  script/src/interpreter.rs
  script/src/num.rs
  script/src/opcode.rs
Labels: A8-looksgood, M4-core

#499 Distinguish BTC and BCH
  README.md
  bencher/src/verifier.rs
  message/src/message/message_header.rs
  network/src/consensus.rs
  network/src/network.rs
  p2p/src/io/handshake.rs
  p2p/src/io/read_any_message.rs
  p2p/src/io/read_header.rs
  p2p/src/io/read_message.rs
  pbtc/cli.yml
  pbtc/config.rs
  sync/src/blocks_writer.rs
  sync/src/local_node.rs
  sync/src/synchronization_chain.rs
  sync/src/synchronization_client_core.rs
  sync/src/synchronization_verifier.rs
  tools/regtests.sh
  verification/src/accept_transaction.rs
  verification/src/chain_verifier.rs
  verification/src/work_bch.rs
Labels: A8-looksgood, M2-config, M3-docs, M4-core

#497 Bitcoin Cash: OP_NUM2BIN implementation
  Cargo.lock
  script/src/error.rs
  script/src/flags.rs
  script/src/interpreter.rs
  script/src/opcode.rs
  storage/Cargo.toml
  storage/src/lib.rs
Labels: A0-pleasereview, M4-core
