Repository paritytech/parity-bitcoin, pull requests merged in 2018-05, with the labels that each got.

#503 Fix typo
  p2p/src/config.rs
Labels: A2-insubstantial, M3-docs

#506 Fix witness commitment size check
  script/src/script.rs
Labels: A0-pleasereview, F0-consensus, M4-core

#501 Bitcoin Cash: monolith activation
  network/src/consensus.rs
  sync/src/local_node.rs
  verification/src/accept_block.rs
  verification/src/accept_chain.rs
  verification/src/accept_transaction.rs
  verification/src/chain_verifier.rs
  verification/src/lib.rs
  verification/src/work_bch.rs
Labels: A0-pleasereview, F0-consensus

#509 Update lazy_static dependencies to 1.0
  Cargo.lock
  keys/Cargo.toml
  network/Cargo.toml
  verification/Cargo.toml
Labels: A0-pleasereview, M4-core

#511 Fixed duplicate transaction hashes in bencher
  bencher/src/database.rs
  bencher/src/verifier.rs
Labels: A8-looksgood
