Repository paritytech/parity-bitcoin, pull requests merged in 2018-03, with the labels that each got.

#486 Replace try! with ? in script
  script/src/interpreter.rs
  script/src/script.rs
  script/src/stack.rs
Labels: A2-insubstantial, M4-core

#490 Bitcoin Cash: OP_DIV and OP_MOD implementation
  primitives/src/bytes.rs
  script/src/error.rs
  script/src/flags.rs
  script/src/interpreter.rs
  script/src/num.rs
  script/src/opcode.rs
Labels: A0-pleasereview, M4-core

#494 fix CI lint
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-patch, M1-ci
