Repository paritytech/parity-bitcoin, pull requests merged in 2019-03, with the labels that each got.

#544 update tags in CI and test gihub integration
  .gitlab-ci.yml
Labels: A0-pleasereview, B0-patchthis, M1-ci

#547 Allow zero fee transactions on regtest network
  miner/src/memory_pool.rs
  sync/src/lib.rs
Labels: A0-pleasereview, M4-core

#546 Full refactoring CI
  .gitlab-ci.yml
  snap/snapcraft.yaml
Labels: A0-pleasereview, M1-ci

#550 new snapcraft template
  .gitlab-ci.yml
  snap/snapcraft.yaml
  tools/docker_build.sh
  tools/ver.sh
Labels: M1-ci
